const routes = {
    shop: '/',
    news: '/news',
    about: '/about',
    returnpolicy: '/chinh-sach-doi-tra',
    privacypolicy: '/chinh-sach-bao-mat',
    termsservice: '/dieu-khoan-dich-vu',
    contact: '/contact',
    infostore: '/thong-tin-cua-hang',
    starrate: '/danh-gia-khach-hang',
    sale: '/sale',
    register: '/register',
    forgetpassword: '/quen-mat-khau',
    cart: '/cart',
    details: '/product/:id',
    payment: '/payment',
    collect: '/collect',
    collecttop: 'collecttop',
    collectbot: 'collectbot',
    admin: '/admin',
    user: '/admin/user',
    product: '/admin/product',
    order: '/admin/order',
    categorys: '/admin/category',

    singleuser: '/users/:id',
    singleproduct: '/products/:id',
    users: '/users',
    products: '/products',
    newuser: 'users/new-user',
    edituser: 'User/EditUser/:id',
    editproduct: 'Product/EditProduct/:id',
    editcategory: 'Category/EditCategory/:id',

    newproduct: 'product/new-product',
    orders: '/orders',
    newcategorys: 'categorys/new-categorys',

    categorys: '/categorys',
    profile: '/profile',

    // login: '/admin/login',
    // list: '/admin/users/list',
    // single: '/admin/users/:userId',
    // new: '/admin/users/new',
    // product: '/admin/product/list',
    // productId: '/admin/product/:productid',

    // profile: '/@:nickname',
};

export default routes;
