const routes = {
    shop: '/',
    news: '/news',
    about: '/about',
    returnpolicy: '/chinh-sach-doi-tra',
    privacypolicy: '/chinh-sach-bao-mat',
    termsservice: '/dieu-khoan-dich-vu',
    contact: '/contact',
    infostore: '/thong-tin-cua-hang',
    starrate: '/danh-gia-khach-hang',
    sale: '/sale',
    register: '/register',
    forgetpassword: '/quen-mat-khau',
    cart: '/cart',
    details: '/product/:id',
    payment: '/payment',
    admin: '/admin',
    users: '/users',
    single: '/users/single',
    collect: '/collect',
    collecttop: 'collecttop',
    collectbot: 'collectbot',
    // login: '/admin/login',
    // list: '/admin/users/list',
    // single: '/admin/users/:userId',
    // new: '/admin/users/new',
    // product: '/admin/product/list',
    // productId: '/admin/product/:productid',

    // profile: '/@:nickname',
};

export default routes;
